### ISSUE TITLE
[Enhancement] PlotChat support

### ISSUE THREAD

**Issue by veldik** [Oribuin/ChatEmojis#1]
Add PlotSquared plotchat support

![image](https://user-images.githubusercontent.com/37436112/86169693-4dfa1400-bb1a-11ea-9cb9-e3d6d9a0ea5d.png)

**Comment by Oribuin** [comment]
I’ll work on this for ChatEmojis 1.10

Edit: Quick note for the next update on this plugin, I've removed support for colors in emojis so that may cause you a few issues n the future

**Comment by veldik** [comment]
It is working 
![image](https://user-images.githubusercontent.com/37436112/88726349-d5dd3900-d12d-11ea-9345-e8c772782f91.png)
